name: Fix Network Connectivity

on:
  workflow_dispatch:

jobs:
  fix-connectivity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Fix Network ACLs for VPC Communication
      run: |
        echo "🔧 Corrigindo Network ACLs para permitir comunicação interna na VPC..."
        
        # Obter as NACLs das subnets
        echo "📋 Obtendo Network ACLs das subnets..."
        NACL_IDS=$(aws ec2 describe-subnets --subnet-ids subnet-07fe020cefc4bd241 subnet-08d34ed68511f3917 --query 'Subnets[*].NetworkAclAssociations[*].NetworkAclId' --output text | tr '\t' ' ' | tr '\n' ' ')
        
        for nacl_id in $NACL_IDS; do
          if [ ! -z "$nacl_id" ]; then
            echo "🛠️ Configurando NACL: $nacl_id"
            
            # Verificar se é a NACL padrão
            IS_DEFAULT=$(aws ec2 describe-network-acls --network-acl-ids $nacl_id --query 'NetworkAcls[0].IsDefault' --output text)
            
            if [ "$IS_DEFAULT" = "True" ]; then
              echo "✅ NACL padrão detectada - já deve permitir todo tráfego interno"
            else
              echo "⚠️ NACL customizada detectada - adicionando regras de conectividade"
              
              # Adicionar regra ALLOW para tráfego MySQL (3306) de entrada
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 100 \
                --protocol tcp \
                --rule-action allow \
                --port-range From=3306,To=3306 \
                --cidr-block 172.31.0.0/16 \
                --ingress || echo "Regra de ingresso já existe ou erro"
              
              # Adicionar regra ALLOW para tráfego MySQL (3306) de saída  
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 100 \
                --protocol tcp \
                --rule-action allow \
                --port-range From=3306,To=3306 \
                --cidr-block 172.31.0.0/16 \
                --egress || echo "Regra de egresso já existe ou erro"
              
              # Adicionar regra ALLOW para todo tráfego TCP interno da VPC (ingresso)
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 200 \
                --protocol tcp \
                --rule-action allow \
                --port-range From=0,To=65535 \
                --cidr-block 172.31.0.0/16 \
                --ingress || echo "Regra de ingresso TCP já existe ou erro"
              
              # Adicionar regra ALLOW para todo tráfego TCP interno da VPC (egresso)
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 200 \
                --protocol tcp \
                --rule-action allow \
                --port-range From=0,To=65535 \
                --cidr-block 172.31.0.0/16 \
                --egress || echo "Regra de egresso TCP já existe ou erro"
              
              # Adicionar regra ALLOW para ICMP (ping) interno da VPC (ingresso)
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 300 \
                --protocol icmp \
                --rule-action allow \
                --icmp-type-code Code=-1,Type=-1 \
                --cidr-block 172.31.0.0/16 \
                --ingress || echo "Regra ICMP de ingresso já existe ou erro"
              
              # Adicionar regra ALLOW para ICMP (ping) interno da VPC (egresso)
              aws ec2 create-network-acl-entry \
                --network-acl-id $nacl_id \
                --rule-number 300 \
                --protocol icmp \
                --rule-action allow \
                --icmp-type-code Code=-1,Type=-1 \
                --cidr-block 172.31.0.0/16 \
                --egress || echo "Regra ICMP de egresso já existe ou erro"
            fi
            
            echo ""
            echo "📋 Regras atuais da NACL $nacl_id:"
            aws ec2 describe-network-acls --network-acl-ids $nacl_id --query 'NetworkAcls[0].Entries' --output table
            echo ""
          fi
        done
        
        echo "✅ Configuração das NACLs concluída!"
        echo "🔄 Aguarde alguns minutos para que as alterações sejam propagadas na AWS."