name: Restart Pods for JWT_SECRET

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  restart-pods:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        aws-region: us-east-1

    - name: Restart pods
      run: |
        aws eks --region us-east-1 update-kubeconfig --name $(aws eks list-clusters --region us-east-1 --query 'clusters[0]' --output text)
        kubectl delete pods -l app=fastfood-api --force --grace-period=0
        sleep 10
        kubectl get pods -l app=fastfood-api