name: Test Database Connectivity

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  TF_VERSION: "1.5.0"

jobs:
  test-connectivity:
    name: Test DB Connectivity
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name fast-food-cluster-prd

    - name: Test connectivity with netcat from EKS pod
      run: |
        echo " Testing database connectivity from EKS pod..."
        API_POD=$(kubectl get pods -l app=fastfood-api -o jsonpath="{.items[0].metadata.name}")
        echo "Using pod: $API_POD"
        
        echo ""
        echo " Testing TCP connectivity to RDS..."
        kubectl exec $API_POD -- timeout 10 nc -zv fastfood-db.czyqradinnne.us-east-1.rds.amazonaws.com 3306 || echo "TCP connection failed"
        
        echo ""
        echo " Testing with telnet..."
        kubectl exec $API_POD -- timeout 10 sh -c "echo quit | telnet fastfood-db.czyqradinnne.us-east-1.rds.amazonaws.com 3306" || echo "Telnet failed"
        
        echo ""
        echo " Testing MySQL connection..."
        kubectl exec $API_POD -- timeout 10 sh -c "mysql -h fastfood-db.czyqradinnne.us-east-1.rds.amazonaws.com -u admin -padmin123 -e 'SELECT 1;'" || echo "MySQL connection failed"
